# DeepTrace Logger Configuration

version: 1
disable_existing_loggers: False

formatters:
    default:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: rich.logging.RichHandler
        show_time: False

    file:
        class: logging.handlers.RotatingFileHandler
        formatter: default
        filename: logs/deeptrace.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    main:
        level: INFO
        handlers: [console, file]
        propagate: no

root:
    level: INFO
    handlers: [console, file]
    propagate: no